# raw_master.yml
name: KRX Raw Master

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build RAW Master and Update GSheet
        env:
          # 시크릿 이름을 GCP_CREDENTIALS로 변경
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        run: python build_raw_master.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add DB/raw_mst_krx_full.parquet
          git commit -m "Update RAW Master DB: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
